### ISSUE TITLE
1.18.2, request 

### ISSUE THREAD

**Issue by 78codemonkey** [Psidris/CuriousLanterns#1]
Mc 1.18.2, Forge 40.1.76
Request is for additional lanterns 
To be used in curios slot for hip.

**Comment by Psidris** [comment]
I'm not entirely sure what you mean here. Are you asking to use the curio slot instead of the hip slot?

**Comment by 78codemonkey** [comment]
like how you can use minecraft vanilla lantern for this mod, instead of just vanilla, but also additional lanterns mod to be used in hip slot

**Comment by Psidris** [comment]
Oh, I understand. I can see if it's possible.

**Comment by Psidris** [comment]
Added Additional Lanterns compatibility with 1.1.4, should release on curseforge soon.

**Comment by 78codemonkey** [comment]
Awesome and thanks 😊 🙏
