### ISSUE TITLE
Lanterns not able to be placed in belt slot of Curios.

### ISSUE THREAD

**Issue by robotliar** [Psidris/CuriousLanterns#12]
I have the Lucent, Radiant Gear, and Curious Lanterns installed. For some reason, lanterns can not be inserted into the belt slot of curios.

**Comment by Psidris** [comment]
Would you please provide further information, such as minecraft version, mod version, and a full mod list? In order to undergo proper testing, I need to ensure I have as close to an identical set up to you, otherwise I may not be able to recreate the issue.

For some basic diagnostic:
1. Check to make sure you have Curios installed as well. If you're using Curseforge, then it should install automatically. However, if you are installing mods manually, then you may have missed Curios by accident.
2. Make sure the item you are trying to put in the curios slot has the 'Curio: Belt' item tag, or some variant thereof. Some mods may replace the lantern item itself, giving it a different namespace, thus conflicting with how this mod defines curios compatibility. If the item lacks the Belt item tag, then the item is not inherently compatible with Curious Lanterns, and needs to be added. If this is the case, please inform me of the mod the lantern is from.

**Comment by robotliar** [comment]
Of course, Minecraft 1.19.2, mod version 1.3.3.

"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\awesomedungeonnether-forge-1.19.2-3.1.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\awesomedungeonocean-forge-1.19.2-3.3.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\balm-forge-1.19.2-4.5.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\beachparty-1.0.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\BetterAnimationsCollection-v4.0.5-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\bettercombat-forge-1.7.1+1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\BetterFog-1.19.2-1.1.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\betterfoliage-4.0.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\betterfpsdist-1.19.2-1.8.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\better-mcdonalds-mod-1.19.2-2.0.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\bettervillage-forge-1.19.2-3.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\biomancy-forge-1.19.2-2.1.11.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\biomemusic-1.19.2-1.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\BlockRunner-v4.2.2-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\blueprint-1.19.2-6.1.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Bookshelf-Forge-1.19.2-16.3.20.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\botarium-forge-1.19.2-1.8.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\brutalbosses-1.19.2-6.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\bwncr-forge-1.19.2-3.14.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\caelus-forge-1.19.2-3.0.0.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\canary-mc1.19.2-0.2.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\capybaramod-0.0.2-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\castle_in_the_sky-1.19.2-0.5.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\chipped-forge-1.19.2-2.1.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\chromaticarsenal-1.19.2-1.7.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\citadel-2.1.4-1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\clean_tooltips-1.3-forge-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\cloth-config-8.2.88-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Clumps-forge-1.19.2-9.0.0+14.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\collectorsalbum-forge-1.19.2-1.5.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Compressium-2.1.1-build.8+mc1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\configuration-forge-1.19.2-2.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\connectivity-1.19.2-4.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\constructionwand-1.19.2-2.10.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Continents_1.19.3_v1.1.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Controlling-forge-1.19.2-10.0+7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\CorgiLib-forge-1.19.2-1.0.0.34.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\CosmeticArmorReworked-1.19.2-v1a.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\CraftTweaker-forge-1.19.2-10.1.45.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\create_central_kitchen-1.19.2-for-create-0.5.1.b-1.3.7.c.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\create-1.19.2-0.5.1.b.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\CTM-1.19.2-1.1.6+8.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\curios-forge-1.19.2-5.1.4.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\curiotiab-1.19.2-1.5.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\curiouslanterns-1.19.2-1.3.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\davespotioneering-1.19.2-1.1.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Decorative Blocks-forge-1.19.2-3.0.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\deeperdarker-forge-1.1.6-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Ding-1.19.2-Forge-1.4.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\doapi-forge-1.0.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\DoggyTalents-1.19.2-2.6.10.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\dotcoinmod-forge-19.15.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Droplight-1.19.2-forge-1.0.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\dynview-1.19.1-2.9.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\EasyAnvils-v4.0.11-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\EasyMagic-v4.3.3-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\emi-1.0.4+1.19.2+forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\EnchantingInfuser-v4.2.2-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\entityculling-forge-1.6.1-mc1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\epicsamurai-0.0.13-1.19.2-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\EquipmentCompare-1.19.2-forge-1.3.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ExplorersCompass-1.19.2-1.3.0-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\fabric-api-0.83.0+1.19.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Fallingleaves-1.19.1-1.3.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\FarmersDelight-1.19-1.2.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\farsight-1.19.2-2.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\FastLeafDecay-30.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\FastSuite-1.19.2-4.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ferritecore-5.0.3-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\flywheel-forge-1.19.2-0.6.8.a.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-chunks-forge-1902.3.22-build.271.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-essentials-1902.1.10-build.47.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-library-forge-1902.3.19-build.214.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-quests-forge-1902.4.16-build.235.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-teams-forge-1902.2.13-build.100.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ftb-ultimine-forge-1902.4.0-build.77.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\geckolib-forge-1.19-3.1.40.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\geodeforge-1.1.8-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\geophilic-1.19-2.0.0c.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Good Ending-1.19.2-1.0.2-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\gravestone-1.19.2-1.0.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\guardvillagers-1.19.2-1.5.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\habitat-1.2.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\handcrafted-forge-1.19.2-2.0.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\HangGlider-v4.0.0-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\hexerei-0.3.2.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Iceberg-1.19.2-forge-1.1.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\idas_forge-1.7.4+1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\immersive_paintings-0.6.1+1.19.2-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Incendium_1.19.3_v5.1.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ineedblock-0.0.9beta-1.9.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\infernal-expansion-1.19.2-2.5.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\integrated_api_forge-1.2.7+1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\integrated_stronghold_forge-1.0.2+1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ironchest-1.19.2-14.2.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\irons_spellbooks-1.19.2-1.1.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ItemBorders-1.19.1-1.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\itemcollectors-1.1.7-forge-mc1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\item-filters-forge-1902.2.9-build.51.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Jade-1.19.1-forge-8.8.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\JadeAddons-1.19.2-forge-3.5.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\jei-1.19.2-forge-11.6.0.1015.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\jmi-forge-1.19.2-0.13-33.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\journeymap-1.19.2-5.9.7-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\JustEnoughResources-1.19.2-1.2.2.200.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\keebszs_battle_towers-0.5.0-1.19.x.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Kiwi-1.19.1-forge-8.3.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\kotlinforforge-3.12.0-all.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\L_Enders_Cataclysm-0.84-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\LegendaryTooltips-1.19.2-forge-1.4.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\libraryferret-forge-1.19.2-4.0.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\lightspeed-1.19.2-1.0.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\liquidburner-1.19.2-0.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\loot_journal-2.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\lootintegrations-1.19-3.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\lootr-1.19-0.4.24.62.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\lucent-1.19.2-1.4.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Masik'sPuzzleDungeon-forge-1.19.2-v1.0.7.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\MaxHealthFix-Forge-1.19.2-8.0.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\meetyourfight-1.19.2-1.3.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\memoryleakfix-forge-1.17+-1.0.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\modernfix-forge-5.0.2+mc1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\moonlight-1.19.2-2.2.38-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\MouseTweaks-forge-mc1.19-2.23.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\MutantMonsters-v4.0.6-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\mutantmore-1.19.2-early-access-1.0.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\mutil-1.19.2-5.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\MyServerIsCompatible-1.19-1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\naturalist-forge-3.0.3a-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\NaturesCompass-1.19.2-1.10.0-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Neat-1.19-32.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\NekosEnchantedBooks-1.19-1.8.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\netherportalfix-forge-1.19-10.0.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\nock_enough_arrows-1.19.2-1.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Nullscape_1.19.3_v1.2.1a.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\oculus-flywheel-compat-1.19.2-0.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\oculus-mc1.19.2-1.6.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\OverflowingBars-v4.0.1-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\PassableFoliage-1.19.1-forge-5.2.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\PassiveSkillTree-1.19.2-BETA-0.4.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Patchouli-1.19.2-77.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\paucal-forge-1.19.2-0.5.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Paxi-1.19.2-Forge-3.0.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Placebo-1.19.2-7.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\player-animation-lib-forge-1.0.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\plushies-1.2-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\pocketstorage-1.19-1.0.2-build.23.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\polymorph-forge-0.46.1+1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\pots_and_mimics_rpg_1.0.0_forge_1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Prism-1.19.1-1.0.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\proficiency-1.2.0-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\PuzzlesLib-v4.4.2-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Quark-3.4-405.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\questsadditions-1.19.2-1.4.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\radiantgear-forge-2.0.1+1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\randomium-1.19.2-1.21.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\ReAuth-1.19-Forge-4.0.7.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\relics-1.19.2-0.4.7.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\resourcefullib-forge-1.19.2-1.1.24.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\responsiveshields-2.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Revised Phantoms 1.0.4 - 1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\roadlesstraveled_v1.1-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\rpglevels-0.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\rubidium-0.6.2b.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\saturn-mc1.19.2-0.0.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\secrets_of_forging_revelations-1.1.0-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\SimpleStorageNetwork-1.19.2-1.7.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\SimplyHouses-1.1.3-1.19-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\simplylight-1.19.2-1.4.5-build.42.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\smoothboot(reloaded)-mc1.19.2-0.0.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\smoothchunk-1.19.1-2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\solsweetpotato-1.19.2-2.0.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Special Drops 1.0.1 - 1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\SpelunkingBags1.19_V1.0.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\spirit-forge-1.19.2-2.2.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\spoornarmorattributes-2.0.9-1.19-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\starlight-1.1.1+forge.cf5b10b.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\StorageDrawers-1.19-11.1.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\strongfarmland-1.19-1.1.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Structory_1.19.3_v1.3.1a.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\supermartijn642configlib-1.1.6b-forge-mc1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\supermartijn642corelib-1.1.9a-forge-mc1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\supplementaries-1.19.2-2.3.18.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\suppsquared-1.19.2-1.1.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\sushigocrafting-1.19.2-0.3.8.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\takesapillage-1.0.3-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tarotcards-1.19.2-1.2-release.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tectonic-mod-mc1.19.2-v1.1.10.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tempad-forge-1.19.2-1.4.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\TerraBlender-forge-1.19.2-2.0.1.136.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Terralith_1.19.3_v2.3.8.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tetra-1.19.2-5.2.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tetranomicon-1.4.2-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tetratic-combat-1.19-2.6.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\time-in-a-bottle-3.0.1-mc1.19.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Tips-Forge-1.19.2-8.0.27.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\titanium-1.19.2-3.7.3-27.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\tlc_forge-1.0.2-R-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\toolbooster-1.0-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\TravelersBackpack-1.19.2-8.2.27.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\TravelersTitles-1.19.2-Forge-3.1.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\UndeadUnleashed-1.0.3-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\UniversalBoneMeal-v4.2.0-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\UniversalEnchants-v4.2.15-1.19.2-Forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\upgradedcore-1.19.2-4.1.0.1-release.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\upgradednetherite_ultimate-1.19.2-4.1.0.4-release.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\upgradednetherite-1.19.2-5.1.0.9-release.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\useless-sword-1.19.2-V1.4.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\v_slab_compat-1.19.2-1.4.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\vex_remodel-1.19-1.0.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\vinery-forge-1.3.1.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\Voidscape-1.19.2-0.2.119.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\wandering-bags-1.19.2-2.0.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\waystones-forge-1.19.2-11.4.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\windswept-1.19.2-2.2.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\witheringboon-1.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\WitherSkeletonTweaks-1.19.2-8.0.3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\yippee-1.3.1-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsApi-1.19.2-Forge-3.8.9.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterDungeons-1.19.2-Forge-3.2.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\YungsExtras-1.19.2-Forge-3.1.0.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\AI-Improvements-1.19.2-0.5.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\AkashicTome-1.6-23.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\AmbientEnvironment-forge-1.19.2-8.0+3.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\appleskin-forge-mc1.19-2.4.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\architectury-6.5.85-forge.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\armordamagescale-1.19-2.5.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\armourersworkshop-forge-1.19.2-2.0.0-beta.26.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\art_of_forging-1.6.7-1.19.2.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\AttributeFix-Forge-1.19.2-17.2.6.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\AutoRegLib-1.8.2-55.jar"
"D:\ProgramFiles\Modded Instances\Instances\Animasearch\mods\awesomedungeonend-forge-1.19.2-3.1.1.jar"

**Comment by robotliar** [comment]
Does not give the curios:belt tag to the lantern or the other lanterns.

**Comment by Psidris** [comment]
Unfortunately I cannot seem to replicate the issue. I can safely ascertain that this is not an issue with my mod, but most likely a conflict with one of the mods you have installed, or possibly a config file incorrectly set up. I apologize that I cannot help further.

The only advice I can provide is manually uninstalling each mod until you find the conflict, then reporting it here so I can figure out why it is causing an issue.

**Comment by robotliar** [comment]
Conflict found with the Dot Coin Mod !

**Comment by Psidris** [comment]
After testing it properly (apparently that was the ONE mod that I missed, good job diagnostic me), I can confirm that Dot Coin Mod breaks the Curios Belt slot _specifically_, and not just for Curious Lanterns either. This is purely a Dot Coin Mod issue, and has nothing to do with Curious Lanterns or Curios itself.
I hope you can find a pleasant work around in the meantime.
