### ISSUE TITLE
[1.20.1] Request for compatibility with Chipped and Supplementaries Squared

### ISSUE THREAD

**Issue by TophC7** [Psidris/CuriousLanterns#16]
[Chipped](https://www.curseforge.com/minecraft/mc-mods/chipped) adds a nice variety of pretty unique lamps that I feel would be perfect for this mod. A few of them are really big however and the Iron bowl lanterns specifically are really different so that might be an issue.

![image](https://github.com/psilocke/CuriousLanterns/assets/36116606/3b2b022f-d5d3-456f-a20e-3800af92e648)

[Supplementaries Squared](https://www.curseforge.com/minecraft/mc-mods/supplementaries-squared) is a very popular mod by extension of Supplementaries and only adds 3 pretty basic lanterns.

![image](https://github.com/psilocke/CuriousLanterns/assets/36116606/45fc259f-eb0d-4a7d-9ae4-d2b0a9126751)

Heres a list of the lamps if it helps
```
"chipped:blue_paper_lantern",
"chipped:burning_coal_lantern",
"chipped:checkered_iron_lantern",
"chipped:dark_blue_paper_lantern",
"chipped:ender_lantern",
"chipped:green_paper_lantern",
"chipped:iron_bowl_lantern",
"chipped:purple_paper_lantern",
"chipped:red_paper_lantern",
"chipped:small_green_lantern",
"chipped:white_paper_lantern",
"chipped:wooden_cage_lantern",
"chipped:wrought_iron_lantern",
"chipped:yellow_tube_lantern",
"chipped:blue_paper_soul_lantern",
"chipped:blue_tube_soul_lantern",
"chipped:checkered_iron_soul_lantern",
"chipped:golden_paper_soul_lantern",
"chipped:gray_paper_soul_lantern",
"chipped:iron_bowl_soul_lantern",
"chipped:lime_paper_soul_lantern",
"chipped:orange_paper_soul_lantern",
"chipped:small_red_soul_lantern",
"chipped:wooden_cage_soul_lantern",
"chipped:yellow_paper_soul_lantern",
"chipped:big_lantern",
"chipped:donut_lantern",
"chipped:tall_lantern",
"chipped:wide_lantern",
"chipped:big_soul_lantern",
"chipped:donut_soul_lantern",
"chipped:tall_soul_lantern",
"chipped:wide_soul_lantern"

"suppsquared:copper_lantern",
"suppsquared:crimson_lantern",
"suppsquared:brass_lantern",
```

Awesome mod btw really makes Minecraft so much more enjoyable. thanks :D

**Comment by Psidris** [comment]
These will be included in the upcoming update.
I will mention that the big, donut, tall, and wide lanterns will NOT be included due to a block model and placement glitch.
Thank you for taking the time to find the item names, it made it much easier.
