### ISSUE TITLE
needs to be updated to match the new api

### ISSUE THREAD

**Issue by FullMetalMaster** [Psidris/CuriousLanterns#17]
this mod doesnt work on hip with sodiumdynamiclight 1.0.0. on word in 1.20.1

**Comment by FullMetalMaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/ryoamiclights/comments

RyoamicLights fixes the issue with the hip light

**Comment by Psidris** [comment]
Lighting compatibility is not handled by this mod. Please refer to Radiant Gear for dynamic lighting compatibility.
