### ISSUE TITLE
[1.18.2] Request for compatibility with Quark

### ISSUE THREAD

**Issue by KazuMurako** [Psidris/CuriousLanterns#2]
Add Paper Lanterns from [Quark](https://github.com/VazkiiMods/Quark) to the list of lanterns that are supported by default. I have used a datapack to add them myself, but they do not render on the player in 3rd person or on other players in multiplayer. If the rendering issue is not an issue with your mod, please point me to the proper mod page to report the issue to.

**Comment by Psidris** [comment]
Quark paper lanterns should be implemented in 1.1.5. The base models are a bit too large for the hip normally, so I had to scale them down. It may be a bit weird but I tried my best to ensure the scale wasn't too disproportional.
