### ISSUE TITLE
[1.18.2] Request for compatibility with Macaw's Lights and Lamps

### ISSUE THREAD

**Issue by KazuMurako** [Psidris/CuriousLanterns#3]
Add Paper Lanterns (and whatever other lights from the mod you see fit) from [Macaw's Lights and Lamps](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps) to the list of lights that are supported by default. Same situation as issue https://github.com/psilocke/CuriousLanterns/issues/2

**Comment by Psidris** [comment]
After some time and attempts to add compatibility, I could not successfully integrate a hip model for the paper lanterns. My appologies.
