### ISSUE TITLE
No light emitting....

### ISSUE THREAD

**Issue by Nochala** [Psidris/CuriousLanterns#4]
I have all of the requirements though I don't have curious lights, the name is now radiant gear. Therfor I have radiant gear since that supports 1.19.2. I also don't have any of the incompatible mods aswell and am very confused to why this is not working.  Heres picture down here for reference
![Java-runtime-gamma Screenshot 2022 10 16 - 13 58 51 03](https://user-images.githubusercontent.com/82243395/196050686-ec1ae54b-536b-4885-84f6-f63a631b9905.png)

Please reply as I would love for this mod to work as it did before.

MY MOD LIST:

![Java-runtime-gamma Screenshot 2022 10 16 - 14 02 27 01](https://user-images.githubusercontent.com/82243395/196050820-3c1386a9-c64d-4d6b-a0dd-74d2eeb581de.png)

**Comment by Psidris** [comment]
Did you add the lantern item to the 'dynamiclights_selflight' config file?

**Comment by Nochala** [comment]
The one part of the description I didn't read, thanks...
