### ISSUE TITLE
Not working T_T

### ISSUE THREAD

**Issue by iobiarg** [Psidris/CuriousLanterns#6]
Hi there! 
First, thanks for your mod. 
Second, France (that's for Argentinian folks) XD, 
Third, I apologize beforehand if this is a mistake on my side or a stupid report.

OK, I'm using:
MC 1.19.2
forge-1.19.2-43.2.8
oculus-mc1.19.2-1.2.8a
rubidium-0.6.2a
rubidium_extras-1.19.2_v1.3.2
radiantgear-forge-2.0.1+1.19.2
curios-forge-1.19.2-5.1.3.0
curiouslanterns-1.19.2-1.2.2

I guess that's all that's necessary to have this mod to work- But it isn't. Lanterns work while in hand but not when in the hip slot.

Let me know if there is any other information that I could provide.

**Comment by Psidris** [comment]
It looks like you're missing a dynamic lights mod. 

Rubidium doesn't support dynamic lighting natively), so a mod was made as a patch, called "Magnesium/Rubidium Dynamic Lights".

You will need to install a compatible dynamic lights mod (check the Radiant Gear page to see compatible options). It does not need to be the rubidium specific patch to work, it could be any of the options there, as long as its available. Different mods will have different limitations, an example being i believe "Dynamic Lights", which requires you to manually add the lantern as a dynamic light item. So experiment and find something that works.

If you still encounter issues after installing a dynamic lights mod, do bare in mind that this matter is entirely out of my control. Curious Lanterns only adds the hip slot and a lantern model while equipped. Radiant Gear handles all dynamic lighting. So please submit further issues to the Radiant Gear.

**Comment by iobiarg** [comment]
Oh, thanks. 
I'll search for that mod. I thought that Rubidium already had it. I stopped using Optifine last year because it wasn't working properly with my GPU, (I used that for the past decade) and I'm new to this "oculus+rubidium+shader+this+that".

So thanks, I appreciate you taking the time to answer me. Big hugs from Argentina.
