### ISSUE TITLE
[1.18.2] Request for compatibility with Skinned Lanterns

### ISSUE THREAD

**Issue by Dr-WeiAL** [Psidris/CuriousLanterns#7]
[Skinned Lanterns](https://www.curseforge.com/minecraft/mc-mods/skinned-lanterns)
I checked the previous issues and did not find this mod, and then it is much smaller compared to Quark's lantern, but still larger than the vanilla lantern, I do not know if it is compatible
![image](https://user-images.githubusercontent.com/47446553/233246135-a47630aa-11c9-42e0-a1ac-279a260a97d4.png)

Also I noticed that Macaw's Lights and Lamps has added some lanterns, this might be compatible too?
![image](https://user-images.githubusercontent.com/47446553/233246439-dc1fa914-e8d9-4f3c-91ff-81a7f1c1ccf6.png)

**Comment by Psidris** [comment]
All lantern mods are technically compatible, they may just result in strange interference with the player model.
Ive attempted to add compatibility for Skinned Lanterns in the past, but it resulted in very strange and unappealing hip models, such as certain skinned lanterns either being large and taking up much of the player model, or being too small, rendering details unnoticeable.

I can go ahead and work on adding compatibility for Macaw's Lights, but it is unlikely I will return to Skinned Lanterns in the future.

**Comment by Dr-WeiAL** [comment]
Well, I found that Skinned Lanterns lanterns are the same size as the head, if it looks strange then forget it
![image](https://user-images.githubusercontent.com/47446553/233278657-eb0f8821-5cf1-41a7-9aa5-a0d599ce5653.png)

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/233306213-9f972af3-cd12-4818-ad4a-82df2e5acac1.png)
I put the lanterns from Skinned Lanterns inside large_lanterns and it looks pretty good?

**Comment by Psidris** [comment]
Do the guardian and you'll begin to see the issue. Abnormal shapes are the problem, and yes if people want to use then they can, but it annoys the hell out of me to see it so janky.

If its wanted enough, I'll add support. It just won't be perfect.

**Comment by Dr-WeiAL** [comment]
Uh, I added a medium sized lantern and made it compatible with Skinned Lanterns and have submitted it to Pull requests https://github.com/psilocke/CuriousLanterns/pull/10
![image](https://user-images.githubusercontent.com/47446553/233349647-642b7e12-abb5-4d40-9a02-db041a223dd2.png)

**Comment by Psidris** [comment]
I have encountered render issues regarding some of the soul lantern variants. If i recall, this is what stopped me from continuing in the past, as some soul lanterns use their normal lantern counterpart textures, and my currently system does not account for that due to its automation.

Ive been working trying to find a way to fetch the block texture rather than using a hard coded resource location pointer, but have yet to find a solution. Because of this, Skinned Lanterns combability will have to be postponed until I can find a way to fix the missing textures.

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/233519562-32a906dd-8d62-4502-a1a6-b2a318f9216b.png)
Well I noticed that too, it's really a problem
Unfortunately, I can't help much for now...
